/// Curated list of adjectives for random name generation.
///
/// All entries are lowercase ASCII alphabetic only. No duplicates.
pub(crate) const ADJECTIVES: &[&str] = &[
    "bold", "calm", "dark", "eager", "fair", "gentle", "harsh", "idle", "jolly", "keen", "lame",
    "meek", "neat", "odd", "pale", "quick", "rare", "sly", "tall", "ugly", "vast", "warm", "young",
    "zesty", "able", "brave", "clean", "dense", "empty", "flat", "grand", "happy", "icy", "just",
    "kind", "loud", "mild", "narrow", "open", "plain", "quiet", "rigid", "sharp", "thick", "upper",
    "vivid", "weak", "aged", "bitter", "cool", "deep", "evil", "faint", "grim", "inner", "jaded",
    "known", "lean", "moist", "noble", "oval", "proud", "raw", "soft", "tough", "urban", "vague",
    "wide", "annual", "blind", "crude", "dull", "even", "fine", "gray", "huge", "iron", "joint",
    "lazy", "major", "naive", "only", "polar", "royal", "steep", "tense", "usual", "vital", "worn",
    "acute", "broad", "civil", "dry", "exact", "fresh", "glossy", "heavy", "immune", "junior",
    "late", "magic", "novel", "oily", "petty", "rapid", "sacred", "tired", "ultra", "vain",
    "wicked", "alien", "blunt", "crisp", "dusty", "elastic", "feral", "golden", "hairy", "innate",
    "knotty", "lofty", "merry", "nimble", "ornate", "plump", "rugged", "scenic", "tender", "unfit",
    "vocal", "witty", "bulky", "cozy", "damp", "exotic", "fierce", "greedy", "humble", "irate",
    "jagged", "lumpy", "murky", "nifty", "opaque", "peppy", "robust", "sheer", "timid", "unripe",
    "violet", "wavy", "active", "chunky", "dizzy", "earnest", "flaky", "grumpy", "hearty", "itchy",
    "jerky", "lanky", "moody", "noisy", "perky", "quirky", "roomy", "salty", "tricky", "uneven",
    "wacky", "brainy", "cloudy", "dreamy", "flimsy", "gloomy", "handy", "jumpy", "leafy", "messy",
    "nutty", "pasty", "risky", "shady", "tasty", "untidy", "weary", "zany", "ample", "breezy",
    "curly", "dingy", "edgy", "foggy", "gusty", "hazy", "icky", "juicy", "kinky", "lively",
    "mossy", "nerdy", "oaken", "puffy", "raspy", "silky", "tangy", "uppity", "wiry", "ashen",
    "bushy", "corny", "dainty", "eerie", "funky", "giddy", "husky", "inky", "jazzy", "kooky",
    "loopy", "minty", "nosy", "pesky", "ratty", "snowy", "toasty", "balmy", "chewy", "dewy",
    "floppy", "grainy", "hefty", "ivory", "leggy", "muggy", "pithy", "rusty", "sandy", "tidy",
    "vulgar", "wooly", "ablaze", "benign", "cosmic", "devout", "fickle", "frigid", "gaudy",
    "jovial", "livid", "molten", "placid", "quaint", "serene", "stoic", "torrid", "absurd",
    "candid", "docile", "elated", "filthy", "gifted", "horrid", "latent", "lucid", "morbid",
    "putrid", "rancid", "shrewd", "sordid", "supple", "tawdry", "torpid", "turbid", "pallid",
    "squalid", "superb", "timely", "wanton", "woeful", "astute", "brutal", "clever", "dismal",
    "feeble", "futile", "ghastly", "greasy", "hostile", "insane", "lethal", "mortal", "casual",
    "dental", "fabled", "fiscal", "global", "neural", "primal", "social", "tribal", "verbal",
    "visual", "formal", "rental", "coastal", "digital", "eternal", "snappy", "sturdy", "frosty",
    "steamy", "thorny", "stormy", "snarky", "trashy",
];
